name: restaurant
description: "Restaurant"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  alarm: ^4.0.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1
dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  generate: true
